public class EstdateCalc {
    
    public void calc(Id PhaseId){
        
      //  List<Project_Phase__c> Phaselst = [Select id,Name,Dependencies__c from Project_Phase__c 
             //                     where Phase_Num__c >: pnum and Project__c =: Phase.Project__c];
        
       //  Integer pnum = Phase.Phase_Num__c.intValue();
                       
           //            phselst = [Select id,Name,Dependencies__c from Project_Phase__c 
            //                      where Phase_Num__c >: pnum and Project__c =: Phase.Project__c];
//                        
        
    }

}