/* Class Name: JsonClass
 * Purpose :to read all the values
 * Created on and By :16th Jun 2019, Sridevi
 * Last Modified on and By: 20th Jun 2019, Sridevi
 */
public class JsonClass {
	public String UsageRateCode;
    public String ClientName;
    public String ProjectName;
    public String TeamLeaderUserID = 'Admin';
    public Date StartDate;
    public Date EndDate;
    public Integer BillingType = 2;
    public Integer EffortInDays = 0;
    public Integer RevenueInDoller = 0;
    public String Description;
    public Integer ProjectStatus = 1;
    public Boolean IsChickpeaSOW;
    public String FacilityID = '59a53f0c6077b2a029c52b7f';
    public Boolean IsActive = true;
    // public Bestir_accDetails Account = new Bestir_accDetails();
    
    public String AccName;
    public String ContactPerson;
    public String EmailID;
    public String ClientLocation;
    public String PhoneNumber;
   /* public String AccCity;
    public String AccPhone;
    public String AccEmail;*/
    
}