public class JsonWrapper_Pms{
    public String UsageRateCode;
    public String ClientName;
    public String ProjectName;
    public String TeamLeaderUserID = 'Admin';
    public string StartDate;
    public string EndDate;
    public String BillingType = '2';
    public Integer EffortInDays = 0;
    public Integer RevenueInDoller = 0;
    public String Description;
    public Integer ProjectStatus = 1;
    public Boolean IsChickpeaSOW=false;
    public String FacilityID = '59a53f0c6077b2a029c52b7f';
    public Boolean IsActive = true;
    public Decimal EstimatedHrs=0;
    public String ProjectPhase;    
    // public Bestir_accDetails Account = new Bestir_accDetails();
    public String usageid;
    public String AccName;
    public String ContactPerson;
    public String EmailID;
    public String ClientLocation;
    public String PhoneNumber;
   /* public String AccCity;
    public String AccPhone;
    public String AccEmail;*/
    
}